#!/usr/bin/env ruby

args = ARGV.join(' ')

File.open('ct.log', 'a') do |io|
  io.puts args
end

DELIMITER='++++'

stuff = File.read(File.dirname(__FILE__)+"/ct.output").split(DELIMITER)
puts stuff.shift
File.open(File.dirname(__FILE__)+'/ct.output', 'w') { |out| out.puts stuff.join(DELIMITER) }