#!/usr/bin/env ruby

DELIMITER = "\n++++\n"
CLEARTOOL_ARGS_LOG = File.dirname(__FILE__)+'/ct.log'
CLEARTOOL_FAKE_OUTPUT_FILE = File.dirname(__FILE__)+"/ct.output"

def add_fake_output(output_str)
end

if $0 == __FILE__ 

args = ARGV.join(' ')

File.open(CLEARTOOL_ARGS_LOG, 'a') do |io|
  io.puts args
end


stuff = File.read(CLEARTOOL_FAKE_OUTPUT_FILE).split(DELIMITER)
puts stuff.shift
File.open(CLEARTOOL_FAKE_OUTPUT_FILE, 'w') { |out| out.puts stuff.join(DELIMITER) }

end